import Combine
import Foundation

@MainActor
public final class CacheViewModel: ObservableObject {
    @Published public private(set) var report: CacheScanReport?
    @Published public private(set) var isScanning = false
    @Published public var selectedPaths: Set<String> = []

    // Cached derived data — rebuilt only when report changes
    @Published public private(set) var entriesByCategory: [CacheCategory: [CacheEntry]] = [:]
    @Published public private(set) var safeTotalBytes: UInt64 = 0
    @Published public private(set) var safeEntryCount: Int = 0
    @Published public private(set) var topOffenders: [CacheEntry] = []

    private let cacheService: SystemCacheService
    private let auditLog: AuditLogService

    public init(cacheService: SystemCacheService = SystemCacheService(), auditLog: AuditLogService = AuditLogService()) {
        self.cacheService = cacheService
        self.auditLog = auditLog
    }

    public func scan() async {
        isScanning = true
        defer { isScanning = false }

        let service = cacheService
        let result = await Task.detached(priority: .userInitiated) {
            service.scan()
        }.value

        report = result
        selectedPaths = []
        rebuildCaches()
    }

    private func rebuildCaches() {
        let entries = report?.entries ?? []
        var grouped: [CacheCategory: [CacheEntry]] = [:]
        for entry in entries {
            grouped[entry.category, default: []].append(entry)
        }
        for key in grouped.keys {
            grouped[key]?.sort { $0.sizeBytes > $1.sizeBytes }
        }
        entriesByCategory = grouped

        let safeEntries = entries.filter { $0.riskLevel == .safe }
        safeTotalBytes = safeEntries.reduce(0) { $0 + $1.sizeBytes }
        safeEntryCount = safeEntries.count
        topOffenders = Array(entries.sorted { $0.sizeBytes > $1.sizeBytes }.prefix(3))
    }

    public func entries(for category: CacheCategory) -> [CacheEntry] {
        entriesByCategory[category] ?? []
    }

    public func categoryTotal(_ category: CacheCategory) -> UInt64 {
        report?.categoryTotals[category] ?? 0
    }

    public func categoryCount(_ category: CacheCategory) -> Int {
        entriesByCategory[category]?.count ?? 0
    }

    public var selectedEntries: [CacheEntry] {
        (report?.entries ?? []).filter { selectedPaths.contains($0.path) }
    }

    public var selectedTotalBytes: UInt64 {
        selectedEntries.reduce(0) { $0 + $1.sizeBytes }
    }

    public func toggleSelection(_ entry: CacheEntry) {
        if selectedPaths.contains(entry.path) {
            selectedPaths.remove(entry.path)
        } else {
            selectedPaths.insert(entry.path)
        }
    }

    public func selectAll(for category: CacheCategory) {
        let entries = self.entries(for: category)
        for entry in entries {
            selectedPaths.insert(entry.path)
        }
    }

    public func deselectAll(for category: CacheCategory) {
        let entries = self.entries(for: category)
        for entry in entries {
            selectedPaths.remove(entry.path)
        }
    }

    public func selectAllSafe() {
        guard let report else { return }
        for entry in report.entries where entry.riskLevel == .safe {
            selectedPaths.insert(entry.path)
        }
    }

    public func deselectAll() {
        selectedPaths.removeAll()
    }

    public func cleanupCommands() -> [String] {
        selectedEntries.map { entry in
            "rm -rf \(ShellEscaper.quote(entry.path))"
        }
    }

    public func logCleanup(itemCount: Int) {
        let paths = selectedEntries.map(\.path)
        let totalSize = selectedTotalBytes
        let log = auditLog
        let entry = AuditLogEntry(
            action: .cacheCleanup,
            details: "Cleaned \(itemCount) cache item(s)",
            paths: paths,
            totalBytes: totalSize,
            itemCount: itemCount,
            userConfirmed: true
        )
        Task.detached { log.log(entry) }
    }

    public func executionRequest() -> ExecutionRequest {
        let items = selectedEntries.map { entry in
            ExecutionItem(label: entry.name, path: entry.path, sizeBytes: entry.sizeBytes)
        }

        let cautionCount = selectedEntries.filter { $0.riskLevel == .caution }.count
        let risk: ExecutionRisk = cautionCount > 0 ? .danger : .moderate

        var warning = "You are about to permanently delete \(items.count) cache folders totaling \(ByteFormatting.string(selectedTotalBytes))."
        if cautionCount > 0 {
            warning += "\n\n\(cautionCount) item(s) are marked CAUTION and may contain important data. Deletion is PERMANENT and IRREVERSIBLE."
        } else {
            warning += "\n\nThese are cache files that will be regenerated by their applications. However, deletion is PERMANENT."
        }

        return ExecutionRequest(
            title: "Delete Selected Caches",
            warningMessage: warning,
            risk: risk,
            items: items,
            commands: cleanupCommands(),
            confirmationWord: cautionCount > 0 ? "DELETE" : "CONFIRM"
        )
    }
}
